### ISSUE TITLE
ECDSA_verify error

### ISSUE THREAD

**Issue by jfrey-ntia** [twardokus/v2verifier#56] opened 2023-03-27 14:51 UTC
I'm trying to get v2verifier up and running using DSRC. I have built v2verifier on both machines and can run both flow graphs. The transmit side appears to work fine, but the receive side quits on the first packet that it receives saying `Fatal error: ECDSA_verify returned -1: Bad address`. What could be causing this?

**Comment by twardokus** [comment] 2023-05-15 18:46
Thank you for raising this issue. The cause is due to a bug in the encoding and decoding process used to transmit data using sockets between V2Verifier and GNURadio. A fix has been developed and will be included in an imminent patch.

**Closed** 2023-07-20 17:32 UTC
Labels: bug
